CLIxIndia-Dev/clix_dashboard_ui

src/components/HomeCardsComponent.js
- Text changes in card - Explore state level data
=> solve - Replace the text - Explore State Level Data

src/components/AboutPage.js, src/components/HeaderComponent.js, src/components/LoginPage.js
- **Logout** button added on successful sign in - Tested by Me 
- **Added** / Replace Text In about page - 
- **Email** validation ( dashboard login page ) - empty form c
=> Login button issue solved , added content for about page , email validation login page c

src/components/HeaderComponent.js
- Navbar in mobile view Responsive  ( tested by Me  )
=> solved - Navbar in mobile view (responsive )

package-lock.json, package.json
- added react-helmet component (library) for title of the pages c
=> react-helmet added ( react-library) 

src/components/AboutPage.js, src/components/ContactPage.js, src/components/FAQ.js, src/components/MainComponent.js
The Title of following page is now rendering on hover on browser tab 
- About Page 
- HomePage 
- Contact page 
- FAQ page 
- Will have each title  okay
=> The Helmet element for each component cc

src/components/DropDownMenu.js
**The Test Component for TheschoolMenu **
=> Added Test File For TheSchoolMenu In Components And  Mail File

src/components/MainComponent.js
**Added MainComponent and Solved the Import Issue In main component file c**
=> added maincomponent to solve import issue - C

src/components/TheSchoolAuthe.js
**Added User Function to remove user and replace it in route - C**
=> added user replace function in local storage to reset route - c

src/components/AboutPage.js, src/components/FAQ.js, src/components/FaqPage.js, src/components/HeaderComponent.js, src/components/HomeCardsComponent.js, src/components/TheSchoolAuthe.js
**The following issue in the document is resovled**
- About Page - Text and image is added 
- Faq page double questions and open is solved
- The Navbar Image is replaced with the URL of clix image 
- Home Card - Text is added to update
- TheSchoolDropdown menu update c
=> Updated / Resolved the issue 

src/components/DropAuth.css, src/components/LoginPage.js, src/components/TheSchoolAuthe.js
- Issue about submit button 
- The school name disable till you select all required data
- The Submit form validation 
- Added Styling for submit button 
- Login page username and password error removed on click c
=> The School Disable , Error Message , Submit Button Design And location , Validation - Added C

src/components/HeaderComponent.js, src/services/userservices.js
- User is not removed on refresh. It maintains the state of the user - Login Page
=> Resolved - issue of refresh not keeping user - #12

src/components/LoginPage.js, src/components/TheSchoolAuthe.js
- issue #14 - login page error message 
- issue #13 - text placeholder
=> Added Text in Placeholder and Error message in Login page

src/components/LoginPage.js
=> added error method on change

src/components/TheSchoolAuthe.js
=> The option in school menu disabled if there is no data 

src/components/HeaderComponent.js
the issue of state is solved on Click event in navabar. - Header component page
=> the issue fixed for nav bar click

src/components/DropAuth.css, src/components/Footer.js, src/components/StateHome.js, src/components/TheCLIxM.js, src/components/TheSchoolAuthe.js, src/index.css
- Added new style 
- new lmage
- new title name 
- new component for home page
=> New Component update with footer style 

src/App.css, src/components/Documentation.js, src/components/DropAuth.css, src/components/Footer.js, src/components/HeaderComponent.js, src/components/MainComponent.js, src/components/Privacy.js, src/components/StateHome.js, src/components/TermsofServices.js, src/components/TheCLIxM.js, src/components/thesocialbutton.js
- Added style for the page ( home page)
- Added links for page in the header with newly updated documentation
- Added faq in documentation page and created new route 
- Added links in the social media button 
- Added style for the responsiveness  of the home page
- New component
=> documentation page added with style and link

src/components/Dashboard/ToolsChart.js, src/components/Documentation.js
- Added style for documentation page
=> added style for documentation scroll

src/components/Dashboard/Dashboard.js
- The style changes for responsive charts and module
=> added style and redux attachment

src/components/DropAuth.css, src/components/Footer.js, src/components/HeaderComponent.js, src/components/MainComponent.js, src/components/StateHome.js, src/components/TheSchoolAuthe.js
- the change in the header component - link hover effect, dropdown background image 
- the change in card text
=> added suggested changes in home page

src/components/Dashboard/Dashboard.js, src/components/Dashboard/ImageUpload.js, src/components/DropAuth.css, src/components/Footer.js, src/components/HeaderComponent.js, src/components/LoginPage.js, src/components/StateHome.js, src/components/TheCLIxM.js, src/components/TheSchoolAuthe.js
- The change of responsiveness in-home component 
- The state card
- The tab of clix at glance 
- the active link in header
=> The Change In Home component and Styling, Added active link for header.

public/index.html, src/components/SaveDashboard.js, src/components/TheSchoolAuthe.js
- The tags for seo in home component - c
=> The tags for seo in home component 

public/index.html, src/components/AboutPage.js, src/components/ContactPage.js, src/components/Documentation.js, src/components/DropAuth.css, src/components/FaqPage.js, src/components/Footer.js, src/components/HeaderComponent.js, src/components/MainComponent.js, src/components/Privacy.js, src/components/StateHome.js, src/components/TheCLIxM.js, src/components/TheSchoolAuthe.js
- The state component changes (text)
- The Seo meta tags added in files (text)
- The alt added for image for better SEO (Text)
- The style added for home page 
- The correction in formating of responsive page
=> The new meta tags, new alt for images. and style for home page

public/index.html, src/components/AboutPage.js, src/components/Documentation.js
- The meta tags change for seo in page
=> added new tags -meta tags for share

public/index.html, src/components/TheSchoolAuthe.js
- The dropdown menu in Mozilla wasn't in center solved
=> added new script of meta tags and solve cross browser issue in page

public/index.html, src/components/DropAuth.css, src/components/FAQ.js, src/components/HeaderComponent.js, src/components/StateHome.js, src/components/TheSchoolAuthe.js
> FAQ Question on Hover Color Change
> Add gaps in mobile view #25
> Dropdown not clickable at random times #28 
> Change Case in Title #22
> Submit Button Gap #24
=> The Fixes for issue - #23 #24 #25 #26 #27 #28 

src/components/Documentation.js, src/components/StateHome.js, src/components/TheSchoolAuthe.js
- The alignment of text in a documentation page and mobile 
- The links in state page 
- the gap of button and text etc
- The header component link
=> The Fix for issue reported in project 

src/components/Documentation.js, src/components/DropAuth.css, src/components/TheSchoolAuthe.js
- the state issue in component - solved. 
- The CSS fixed for button in the component 
- The state component CSS solved. 
- The changes in page in the component
=> The fix for state error - Home page

src/components/Documentation.js, src/components/DropAuth.css, src/components/TheSchoolAuthe.js
- The Toc element text 
- The numbers of the data element in documentation data -solved
=> The fix for new issue - documentation page 

Dockerfile, src/config.js
- Added build and serve in dockerfile
- changed the value for 'API_BASE_URL' in config.js
=> Changes related to production build

src/components/DropAuth.css, src/components/TheSchoolAuthe.js
=> Added Search feature in Select Menu  

src/components/Dashboard/Dashboard.js
- The React Lazy for better Rendering of Page 
- The Dashboard page is using it 
-  Added The Sort Method for Filter ( A TO Z ) NO neet to change it from backend
- Using the Fallback gives better Response
=> The Component split using React Lazy for better rending of page

Dockerfile, entrypoint.sh
Created script entrypoint.sh to run while booting the docker container and added it in the dockerfile
=> Changes pertaining to production build

src/components/Documentation.js, src/components/DropAuth.css, src/components/Footer.js, src/components/HeaderComponent.js, src/components/TheCLIxM.js, src/components/thesocialbutton.js
- The att. rel in open link
- The CSS for the header 
This is for best practice and optimization of the component page
=> The addtion of rel and css style for better contract of text in page

public/index.html, public/robots.txt, public/sitemap.xml, src/components/AboutPage.js, src/components/Dashboard/Dashboard.js, src/components/DropAuth.css, src/components/Footer.js, src/components/StateHome.js, src/components/TheCLIxM.js, src/components/TheSchoolAuthe.js, src/components/thesocialbutton.js
- The accessibility  changes 
- The tags as per accessibility , addition of label in filter menu , styling of it 
- The accesiblity and creation of robot file for better SEO , Responsive style in component page
=> The Accessibility changes style + UDISCE code prefixed to the schoolname search dropdown values

src/components/Dashboard/Dashboard.js
- The Button and Text In Description Page 
- The Login issue check u
=>  The dashboard issue in school filter - c

src/components/DropAuth.css, src/components/Footer.js
- The Links in Home page now open in different tab - about page.
=> The footer link in Home page

src/components/Dashboard/Dashboard.js, src/components/DropAuth.css, src/components/Footer.js, src/components/HeaderComponent.js, src/components/LoginPage.js, src/components/MainComponent.js, src/components/PrivateRoute.jsx, src/components/TheSchoolAuthe.js, src/redux/authenticateUser.js, src/redux/fetchmodeactions.js, src/services/dataservices.js, src/services/fetchModeServices.js, src/services/userservices.js
- The position of the CLIx Dashboard 
- The position of the School filter 
- The width of the MIT image in the footer link
- The text in footer links addition of link
=> New LoggedIn User, UI fix, Text Adjustment in Home page

src/components/LoginPage.js, src/services/authHeader.js
- The Note Added In Login Page
- The User added in Component
=> The Note Added In Login Page , User Handing Auth Page

public/index.html, src/components/Dashboard/ModulesChart.js, src/components/Footer.js, src/components/HeaderComponent.js, src/components/TheSchoolAuthe.js
- The Open Graph Image is Updated 
- The MIT logo now has some space
- The Dashboard option in Profile Menu In page
=> The Open Graph , The MIT Logo And The DropDown Dashboard Option in Profile Menu 

src/components/AboutPage.js, src/components/Credits.js, src/components/Footer.js, src/components/LoginPage.js, src/components/Privacy.js, src/components/TermsofServices.js, src/components/TheCLIxM.js, src/components/TheSchoolAuthe.js
- Text and links updated in various component 
- The link in footer element changed  - bug fix in footer component
- The link opens in the new tab - bug fix in about component
- The privacy page scroll id on toc no. 3 - bug fix 
- The link is wrong in the home page footer - bug fix in-home component 
- The Credits page updated with link k- Text and links updated in various component K
=> The Text and links chagnes in Page Component

src/components/Credits.js, src/components/Dashboard/Chart.js, src/components/Dashboard/ModulesChart.js, src/components/Dashboard/PieChartIdleDays.js, src/components/Dashboard/ToolsChart.js, src/components/Documentation.js
- added new correct spellings in dashboard, documentation page
- Added new team members name in credit page
=> Text Changes in Dashboard 
